apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-java-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-java-demo
  template:
    metadata:
      labels:
        app: jenkins-java-demo
    spec:
      containers:
      - name: jenkins-java-demo
        image: registry-vpc.cn-hangzhou.aliyuncs.com/gravity-gold/ack-jenkins-demo:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
